build: build-simulator build-ios

build-simulator:
    xcodebuild archive -scheme A \
        -configuration Release \
        -destination "generic/platform=iOS Simulator" \
        -archivePath ./build/archive/iossimulator.xcarchive \
        -derivedDataPath ./build/simulators \
        -sdk iphonesimulator \
        SKIP_INSTALL=NO \
        BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

build-ios:
    xcodebuild archive -scheme A \
        -configuration Release \
        -destination "generic/platform=iOS" \
        -archivePath ./build/archive/ios.xcarchive \
        -derivedDataPath ./build/iphoneos \
        -sdk iphoneos \
        SKIP_INSTALL=NO \
        BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

clean:
    rm -rf ./build
