build: build-xcframework

build-simulator:
    xcodebuild archive -scheme C \
        -configuration Release \
        -destination "generic/platform=iOS Simulator" \
        -archivePath ./build/archive/iossimulator.xcarchive \
        -derivedDataPath ./build/simulators \
        -sdk iphonesimulator \
        SKIP_INSTALL=NO \
        BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

build-ios:
    xcodebuild archive -scheme C \
        -configuration Release \
        -destination "generic/platform=iOS" \
        -archivePath ./build/archive/ios.xcarchive \
        -derivedDataPath ./build/iphoneos \
        -sdk iphoneos \
        SKIP_INSTALL=NO \
        BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

build-xcframework: build-simulator build-ios
    rm -rf ./build/C.xcframework
    xcodebuild -create-xcframework \
        -framework ./build/archive/iossimulator.xcarchive/Products/Library/Frameworks/C.framework \
        -framework ./build/archive/ios.xcarchive/Products/Library/Frameworks/C.framework \
        -output ./build/C.xcframework

clear:
    rm -rf ./build
